### ISSUE TITLE
docker-compose.yml and conf file are out of date

### ISSUE THREAD

**Issue by digikin** [fluent/fluentd-docs-gitbook#75]
## Description
I just started with fluentd but while attempting to use docker-compose and found that your documentation contains a lot of out dated information. 

Page to be updated - https://docs.fluentd.org/v/0.12/container-deployment/docker-compose#step-0-prepare-docker-compose-yml

## Issues
1. Fluentd build image contained depreceated fluent-plugin-elasticsearch command `--no-rdoc --no-ri` and gem file.
2. The docker image for elasticsearch will return an error if latest is used. 
3. No user configured resulting in permission denied when installing the plugin.
4. No environment configured for elasticsearch resulting in Kibana error
`Unable to revive connection: http://elasticsearch:9200/`
`No living connections`

#### ./fluentd/Dockerfile
```
FROM fluent/fluentd:v1.6-debian-1
USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "3.5.2"]
USER fluent
```
#### docker-compose.yml
```
version: '3'
services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.2.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
```
