### ISSUE TITLE
Copy Container Deployment section in v0.12.0 document to v1.0 document

### ISSUE THREAD

**Issue by ganmacs** [fluent/fluentd-docs-gitbook#76]
ref: https://github.com/fluent/fluentd-docs-gitbook/issues/75

There isn't Container Deployment in v1.0 doc. but 0.12.0 document has it https://docs.fluentd.org/v/0.12/container-deployment

**Comment by digikin** [comment]
## Suggestion to update v1.0 of the documentation for container deployment.  
#### ./fluentd/Dockerfile
1. Update fluent debian version to 1.6
2. Gem install command changed to --no-document and updated gem version.

```
FROM fluent/fluentd:v1.6-debian-1
USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch", "--no-document", "--version", "3.5.2"]
USER fluent
```
#### docker-compose.yml
1. Added envroinment config option per documentation [docker elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) to ignore bootstrap checks for demo purpose. 
```
version: '3'
services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.2.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
```
